name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

  jobs:
    execute-tests:
      name: Checout and execute tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - name: Execute tests
          run: |
              yarn install
              yarn test